# Lecture 4: Species and Speciation & Evolution of Genes and Genomes {-}
 
## Lecture {-}

...

## Ch. 21 Outline {-}

### This is Chapter 22 p. 464-480 (Reconstructing and using phylogenies) in the 9th Edition {-}

### Section 21.1: What is Phylogeny? {-}

1.  Introduction
    1.  A **phylogenetic tree **is a history of evolutionary relationships between organisms. Each split is a point at which one species became two.
    1.  Common ancestor of all organisms in a tree is at the **root**. 
    1.  Any group of species that we name is a **taxon**.
    1.  Any taxon that has all the evolutionary descendants of a common ancestor is a **clade**.
    1.  You can identify clades by picking one point on the tree and following it to the right through all splitting points. 
    1.  Two species that are each other's closest relatives are **sister species**. Two clades that are each other's closest relatives are **sister clades**.
1.  All of life is connected through evolutionary history
    1.  Only about 1.8 million of the tens of millions of species have been named.
1.  Comparisons among species require an evolutionary perspective
    1.  Features shared by two or more species that come from a common ancestor are **homologous**.
    1.  A trait that was already present in the ancestor of a group is known as an **ancestral trait** for the group.
    1.  A trait found in a descendant that differs from the ancestor is a **derived trait**. Derived traits that are shared among a group of organisms is a **synapomorphy. **Vertebral column is an example.
    1.  Not all similar traits are evidence of relatedness:
        1.   Independently evolved traits subjected to similar selection pressures in unrelated species can be similar (wings of bats and birds are not homologous or synapomorphic but are result of **convergent evolution**).
    1.  Similar traits generated by convergent evolution are called **homoplasies (homoplastic traits)**.
    1.  A point may be either **ancestral **or **derived **depending on which point in the phylogeny you are looking at. Feathers are an **ancestral trait **for any taxon of birds because their common ancestor possessed feathers, but if we zoom out and look at a clade that has birds and non-birds that are related by a common ancestor, the trait is a **synapomorphy** and is **derived**.

### Section 21.2 How Are Phylogenetic Trees Constructed? {-}

1.  Introduction
    1.  In a phylogenetic study the group of organisms of primary interest is the **ingroup**. The **outgroup **is a closely related species outside of that group.
    1.  If the outgroup diverged before the ingroup, you can use it to determine which traits of the ingroup are derived and which are ancestral.
    1.  You can look at a set of traits in the ingroup and see which ingroup member has the most traits in common with which other. These will be sister species with a common branch point (the trait).
1.  Parsimony provides the simplest explanation for phylogenetic data
    1.  Under parsimony, the best hypothesis (best phylogenetic tree) is the one that is simplest, and that is the one with the fewest homoplasies.
    1.  Additional evidence is required to incorporate homoplasies and change the tree.
1.  Phylogenies are reconstructed from many sources of data. They are:
    1.  **Morphology:** the presence, size, shape and other attributes of body parts.
        1.  ** **Electron microscopes and computed tomography scans enable systematists to analyze structures of organisms finely.
        1.   Features of morphology that are important for analysis are often specific to the particular group being studied (skeleton for vertebrates, floral structure for flowers).
        1.   Many species look very similar, making morphological classification limited (butterflies).
    1.  **Development**: Similarities in developmental patterns help with classification. Sea squirts only have notochords as larvae, not adults. If we only examined adults we would not be able to relate them to vertebrates which have notochords.
    1.  **Paleontology**: fossils show us where and when organisms lived in the past.
        1.  ** **Provide evidence that helps us distinguish ancestral from derived traits
        1.   Reveals when lineages diverged.
        1.  Groups with few surviving species can have their divergences understood by looking at fossil remains of their ancestors.
    1.  **Behavior: **some behavior is culturally transmitted which is not good for phylogenetic analysis. Others are genetic though (frog calls) and so can be used to distinguish species.
    1.  **Molecular data**: Most phylogenetic analysis today is conducted with genomes.
        1.  ** **The chloroplast genome (cpDNA) has changed slowly over evolution, making it a good candidate for studying ancient organisms. 
        1.   The mitochondrial genome (mtDNA) has changed more rapidly, so it can help us compare closely related species.
1.  Mathematical models expand the power of phylogenetic reconstruction
    1.  Models predict changes in genes. 
    1.  Can predict how a tree might evolve given the data. A **maximum likelihood **method will get a tree that most likely produced the data.
    1.  Most often used with molecular data, not morphology or behavior etc.
1.  The accuracy of phylogenetic methods can be tested
    1.  In one experiment, a single viral culture of bacteriophage T7 was used and lineages were allowed to evolve from this ancestor in the lab.
    1.  The culture was split into two separate lineages, one of these became the ingroup and the other the outgroup. Lineages were allowed to evolve until there were 8. 
    1.  Mutagens were added so the homoplasy and the amount of change would be typical of regular organisms analyzed. 
    1.  They then sequenced the final members of each lineage, and gave the sequences to other investigators without telling them the evolutionary history.
    1.  Phylogenetic methods were shown to be 98-100 percent accurate in reconstructing the phylogenetic tree as it was observed in the lab.

### Section 21.3: How Do Biologists Use Phylogenetic Trees? {-}

1.  Phylogenies help us reconstruct the past
    1.  In flowers, tests based on DNA showed that similar looking flowers are actually part of three different lineages. 
    1.  In humans, HIV was acquired from two different hosts, HIV1 from chimpanzees and HIV2 from sooty mangabeys.
1.  Phylogenies allow us to compare and contrast living organisms
    1.  Swordtail fish males with a long sword are more likely to mate successfully than males with a short sword. 
    1.  One explanation for this is the sensory explanation hypothesis, which is that females already had a preexisting bias for long swords before they evolved.
    1.  To test this a phylogeny identified the swordtail relatives that had split most recently from swordtails before they evolved swords. These were platyfishes. 
    1.  Female platyfishes were attracted to males with a fake long sword attached to them by researchers. This proves the sensory explanation hypothesis.
1.  Ancestral states can be reconstructed
    1.  Researchers used phylogenies to estimate the amino acid sequence of the protein opsin in the ancestor of birds, dinosaurs and crocodiles. They constructed a protein with this sequence and found that it absorbed red light well, suggesting the earlier organism was nocturnal. Thus information about ancestors can be gleaned by recreating their proteins.
1.  Molecular clocks help date evolutionary events
    1.  **Molecular clock hypothesis **says rates of molecular change are constant enough that they can predict evolutionary split times.
    1.  **Molecular clock **uses the average rate at which a given protein accumulates changes to gauge the time of divergence for a particular split in the phylogeny. They must be calibrated using known times of divergence or the fossil record.
    1.  **HIV **has been dated by using a clock calibrated by samples from the 80's and 90's, and tested using samples from the 50's. Clock projected HIV common ancestor at 1930's. Thus AIDS was present in human populations long before the 80's.

### Section 21.4: How Does Phylogeny Relate to Classification? {-}

1.  Introduction
    1.  Before the 1750's, descriptive terms were added to the genus name when a particular species was designated. European honeybee was called Apis pubescens, thorace subgriseo, abdomine fusco, pedibus posticus glabris, utrimque margine ciliatis.
    1.  John Ray developed morphological definition of species (similar physical traits = same species).
    1.  Carl Linnaeus:
        1.   Wrote **systema naturae**. 
        1.   Introduced **binomial nomenclature**
        1.  ** **Believed that species were created by God, and had a **typological species concept** (each species looks different from the other). 
    1.  Problem with the typological species concept: there are differences within species.
    1.  Solution: **biological species concept** defines species in genetic terms: "A group of actually or potentially interbreeding natural populations which are reproductively isolated from other such groups in nature" – Ernst Mayr
    1.  Variation problem is solved by the comparison methods used in the earlier sections.
    1.  In the Linnaean system, there is a hierarchy of taxons: **Kingdom, phylum, class, order, family, genus, **and** species. **Whether a particular taxon is considered a class or order is often a subjective decision.
1.  Evolutionary history is the basis of modern biological classification
    1.  Taxa studied are supposed to be **monophyletic**: include a common ancestor of all the organisms in that group. This is a **clade**.
    1.  A group that does not include its common ancestor is **polyphyletic**. 
    1.  A group that does not include all the descendants of the ancestor is **paraphyletic**.
    1.  A monophyletic group can be removed from a tree by a single cut on a branch.
1.  Several codes of biological nomenclature govern the use of scientific names
    1.  Sometimes taxa have the same names. This is bad. Scientists are trying to use common sets of rules that can be applied across all organisms for naming.

## Reading and Lecture Summary {-}

...

## Lab 4: Protists (Intro to Eukaryotes) {-}